[package]
name = "kairo-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
kairo-core = { path = "../kairo-core" }

clap = { version = "4.5.37", features = ["derive"] }
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "chrono"] }
