[package]
name = "kairo"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15"
chrono = "0.4.41"
diesel-derive-enum = "2.1.0"